<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Cesar Taconeli" />


<title>Módulo 7 - Regressão com covariáveis categóricas</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Gian Lima</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="https://gianlima.github.io/">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Regressão Linear
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Conteúdo de regressão</li>
    <li>
      <a href="regressao_multipla.html">Módulo 3 - Regressão linear múltipla</a>
    </li>
    <li>
      <a href="regressao_outlier.html">Módulo 4 - Técnicas de diagnóstico</a>
    </li>
    <li>
      <a href="regressao_problemas_suposicoes.html">Módulo 5 - Medidas corretivas dos erros</a>
    </li>
    <li>
      <a href="regressao_selecao_modelos.html">Módulo 6 - Seleção de modelos</a>
    </li>
    <li>
      <a href="regressao_categorica.html">Módulo 7 - Regressão com covariáveis categóricas</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/gianlima/r-exams-tutorial">
    <span class="fa fa-github fa-lg"></span>
     
    GitHub
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Módulo 7 - Regressão com covariáveis categóricas</h1>
<h4 class="author">Cesar Taconeli</h4>

</div>


<div id="aula---regressao-linear-com-covariaveis-categoricas." class="section level2">
<h2>Aula - Regressão linear com covariáveis categóricas.</h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" title="1"><span class="kw">head</span>(PlantGrowth)</a></code></pre></div>
<pre><code>##   weight group
## 1   4.17  ctrl
## 2   5.58  ctrl
## 3   5.18  ctrl
## 4   6.11  ctrl
## 5   4.50  ctrl
## 6   4.61  ctrl</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1">PlantGrowth<span class="op">$</span>group &lt;-<span class="st"> </span><span class="kw">factor</span>(PlantGrowth<span class="op">$</span>group, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">&#39;ctrl&#39;</span>, <span class="st">&#39;trt1&#39;</span>, <span class="st">&#39;trt2&#39;</span>))</a></code></pre></div>
<p>Vamos analisar a produção de massa seca sob as três condições experimentais (controle e dois tratamentos).</p>
</div>
<div id="analise-descritiva" class="section level2">
<h2>Análise descritiva</h2>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" title="1"><span class="kw">boxplot</span>(weight <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> PlantGrowth, <span class="dt">xlab =</span> <span class="st">&#39;Grupo&#39;</span>, <span class="dt">ylab =</span> <span class="st">&#39;Horas extras&#39;</span>,</a>
<a class="sourceLine" id="cb4-2" title="2">        <span class="dt">las =</span> <span class="dv">1</span>)</a></code></pre></div>
<p><img src="regressao_categorica_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" title="1"><span class="kw">with</span>(PlantGrowth, <span class="kw">by</span>(weight, group, summary))</a></code></pre></div>
<pre><code>## group: ctrl
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   4.170   4.550   5.155   5.032   5.293   6.110 
## -------------------------------------------------------- 
## group: trt1
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   3.590   4.207   4.550   4.661   4.870   6.030 
## -------------------------------------------------------- 
## group: trt2
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   4.920   5.268   5.435   5.526   5.735   6.310</code></pre>
</div>
<div id="considerar-grupo-controle-e-grupo-com-tratamento" class="section level2">
<h2>Considerar grupo controle e grupo com tratamento</h2>
<p>Vamos considerar, num primeiro momento, apenas o grupo controle e o grupo com tratamento 1 (trt1)</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" title="1">PlantGrowth2 &lt;-<span class="st"> </span><span class="kw">subset</span>(PlantGrowth, group <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;ctrl&#39;</span>, <span class="st">&#39;trt1&#39;</span>))</a>
<a class="sourceLine" id="cb7-2" title="2"></a>
<a class="sourceLine" id="cb7-3" title="3">ajuste1 &lt;-<span class="st"> </span><span class="kw">lm</span>(weight <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> PlantGrowth2)</a>
<a class="sourceLine" id="cb7-4" title="4"><span class="kw">model.matrix</span>(ajuste1)</a></code></pre></div>
<pre><code>##    (Intercept) grouptrt1
## 1            1         0
## 2            1         0
## 3            1         0
## 4            1         0
## 5            1         0
## 6            1         0
## 7            1         0
## 8            1         0
## 9            1         0
## 10           1         0
## 11           1         1
## 12           1         1
## 13           1         1
## 14           1         1
## 15           1         1
## 16           1         1
## 17           1         1
## 18           1         1
## 19           1         1
## 20           1         1
## attr(,&quot;assign&quot;)
## [1] 0 1
## attr(,&quot;contrasts&quot;)
## attr(,&quot;contrasts&quot;)$group
## [1] &quot;contr.treatment&quot;</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" title="1"><span class="kw">summary</span>(ajuste1)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = weight ~ group, data = PlantGrowth2)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.0710 -0.4938  0.0685  0.2462  1.3690 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   5.0320     0.2202  22.850 9.55e-15 ***
## grouptrt1    -0.3710     0.3114  -1.191    0.249    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.6964 on 18 degrees of freedom
## Multiple R-squared:  0.07308,    Adjusted R-squared:  0.02158 
## F-statistic: 1.419 on 1 and 18 DF,  p-value: 0.249</code></pre>
<p>Neste caso, o intercepto corresponde à estimativa do peso médio das plantas do grupo controle (5.03). A segunda estimativa apresentada corresponde à diferença no peso médio de plantas submwetidas ao tratamento 1 em relação a plantas do grupo controle (-0.37). A estimativa para o peso médio de plantas submetidas ao tratamento 1 é calculada por 5.03 - 0.37 = 4.66.</p>
<p>Vamos analisar os dados agora usando um teste t de comparação de médias, assumindo variâncias iguais nos dois grupos.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" title="1"><span class="kw">t.test</span>(weight <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> PlantGrowth2, <span class="dt">var.equal =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  weight by group
## t = 1.1913, df = 18, p-value = 0.249
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.2833003  1.0253003
## sample estimates:
## mean in group ctrl mean in group trt1 
##              5.032              4.661</code></pre>
<p>Observe que o resultado do teste, bem como as estimativas apresentadas, são rigorosamente iguais às produzidas pelo modelo de regressão linear.</p>
</div>
<div id="tres-grupos" class="section level2">
<h2>Três grupos</h2>
<p>Vamos continuar a análise considerando os três grupos.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" title="1">ajuste2 &lt;-<span class="st"> </span><span class="kw">lm</span>(weight <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> PlantGrowth)</a>
<a class="sourceLine" id="cb13-2" title="2"><span class="kw">model.matrix</span>(ajuste2)</a></code></pre></div>
<pre><code>##    (Intercept) grouptrt1 grouptrt2
## 1            1         0         0
## 2            1         0         0
## 3            1         0         0
## 4            1         0         0
## 5            1         0         0
## 6            1         0         0
## 7            1         0         0
## 8            1         0         0
## 9            1         0         0
## 10           1         0         0
## 11           1         1         0
## 12           1         1         0
## 13           1         1         0
## 14           1         1         0
## 15           1         1         0
## 16           1         1         0
## 17           1         1         0
## 18           1         1         0
## 19           1         1         0
## 20           1         1         0
## 21           1         0         1
## 22           1         0         1
## 23           1         0         1
## 24           1         0         1
## 25           1         0         1
## 26           1         0         1
## 27           1         0         1
## 28           1         0         1
## 29           1         0         1
## 30           1         0         1
## attr(,&quot;assign&quot;)
## [1] 0 1 1
## attr(,&quot;contrasts&quot;)
## attr(,&quot;contrasts&quot;)$group
## [1] &quot;contr.treatment&quot;</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" title="1"><span class="kw">summary</span>(ajuste2)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = weight ~ group, data = PlantGrowth)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.0710 -0.4180 -0.0060  0.2627  1.3690 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   5.0320     0.1971  25.527   &lt;2e-16 ***
## grouptrt1    -0.3710     0.2788  -1.331   0.1944    
## grouptrt2     0.4940     0.2788   1.772   0.0877 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.6234 on 27 degrees of freedom
## Multiple R-squared:  0.2641, Adjusted R-squared:  0.2096 
## F-statistic: 4.846 on 2 and 27 DF,  p-value: 0.01591</code></pre>
<p>O intercepto novamente corresponde à estimativa do peso médio de plantas em condições semelhantes às do grupo controle. As demais estimativas correspondem às diferenças nas médias para cada grupo tratado em relação ao grupo controle.</p>
<p>Os resultados não apontam diferença significativa de peso, ao nível de 5%, para plantas submetidas ao tratamento 1 (p = 0.1944) e ao tratamento 2 (p = 0.0877) em relação ao grupo controle.</p>
<p>Vamos usar o teste F da análise de variância para avaliar a diferença entre os grupos.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" title="1"><span class="kw">anova</span>(ajuste2)</a></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: weight
##           Df  Sum Sq Mean Sq F value  Pr(&gt;F)  
## group      2  3.7663  1.8832  4.8461 0.01591 *
## Residuals 27 10.4921  0.3886                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>O teste F indica diferença significativa, ao nível de significância de 5%, para as médias dos três grupos.</p>
<p>Mas o que dizer sobre a diferença dos efeitos dos tratamentos 1 e 2?</p>
<p>Podemos redefinir a categoria de referência da variável grupo:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" title="1">PlantGrowth<span class="op">$</span>group &lt;-<span class="st"> </span><span class="kw">relevel</span>(PlantGrowth<span class="op">$</span>group, <span class="dt">ref =</span> <span class="st">&#39;trt2&#39;</span>)</a>
<a class="sourceLine" id="cb19-2" title="2"></a>
<a class="sourceLine" id="cb19-3" title="3">ajuste3 &lt;-<span class="st"> </span><span class="kw">lm</span>(weight <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> PlantGrowth)</a>
<a class="sourceLine" id="cb19-4" title="4"><span class="kw">model.matrix</span>(ajuste3)</a></code></pre></div>
<pre><code>##    (Intercept) groupctrl grouptrt1
## 1            1         1         0
## 2            1         1         0
## 3            1         1         0
## 4            1         1         0
## 5            1         1         0
## 6            1         1         0
## 7            1         1         0
## 8            1         1         0
## 9            1         1         0
## 10           1         1         0
## 11           1         0         1
## 12           1         0         1
## 13           1         0         1
## 14           1         0         1
## 15           1         0         1
## 16           1         0         1
## 17           1         0         1
## 18           1         0         1
## 19           1         0         1
## 20           1         0         1
## 21           1         0         0
## 22           1         0         0
## 23           1         0         0
## 24           1         0         0
## 25           1         0         0
## 26           1         0         0
## 27           1         0         0
## 28           1         0         0
## 29           1         0         0
## 30           1         0         0
## attr(,&quot;assign&quot;)
## [1] 0 1 1
## attr(,&quot;contrasts&quot;)
## attr(,&quot;contrasts&quot;)$group
## [1] &quot;contr.treatment&quot;</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" title="1"><span class="kw">summary</span>(ajuste3)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = weight ~ group, data = PlantGrowth)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.0710 -0.4180 -0.0060  0.2627  1.3690 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   5.5260     0.1971  28.032  &lt; 2e-16 ***
## groupctrl    -0.4940     0.2788  -1.772  0.08768 .  
## grouptrt1    -0.8650     0.2788  -3.103  0.00446 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.6234 on 27 degrees of freedom
## Multiple R-squared:  0.2641, Adjusted R-squared:  0.2096 
## F-statistic: 4.846 on 2 and 27 DF,  p-value: 0.01591</code></pre>
<p>Há diferença significativa no peso médio de plantas sob os tratamentos 1 e 2. Estima-se, em média, 0.8650 a menos de peso sob tratamento 1 em relação ao tratamento 2.</p>
<p>Ao invés de redefinir o intercepto, vamos usar a função glht do pacote multcomp para estimar a diferença entre os dois tratamentos.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" title="1"><span class="kw">require</span>(multcomp)</a></code></pre></div>
<p>Vamos retomar o ajuste2, em que o grupo controle é a referência.</p>
<p>Estimativa da diferença dos pesos médios sob os tratamentos 1 e 2.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" title="1">L &lt;-<span class="st"> </span><span class="kw">rbind</span>(<span class="st">&#39;Trat 1 - Trat 2&#39;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">-1</span>)); L</a></code></pre></div>
<pre><code>##                 [,1] [,2] [,3]
## Trat 1 - Trat 2    0    1   -1</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" title="1">g2 &lt;-<span class="st"> </span><span class="kw">glht</span>(ajuste2, <span class="dt">linfct =</span> L); g2</a></code></pre></div>
<pre><code>## 
##   General Linear Hypotheses
## 
## Linear Hypotheses:
##                      Estimate
## Trat 1 - Trat 2 == 0   -0.865</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" title="1"><span class="kw">summary</span>(g2)</a></code></pre></div>
<pre><code>## 
##   Simultaneous Tests for General Linear Hypotheses
## 
## Fit: lm(formula = weight ~ group, data = PlantGrowth)
## 
## Linear Hypotheses:
##                      Estimate Std. Error t value Pr(&gt;|t|)   
## Trat 1 - Trat 2 == 0  -0.8650     0.2788  -3.103  0.00446 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## (Adjusted p values reported -- single-step method)</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" title="1"><span class="kw">confint</span>(g2)</a></code></pre></div>
<pre><code>## 
##   Simultaneous Confidence Intervals
## 
## Fit: lm(formula = weight ~ group, data = PlantGrowth)
## 
## Quantile = 2.0518
## 95% family-wise confidence level
##  
## 
## Linear Hypotheses:
##                      Estimate lwr     upr    
## Trat 1 - Trat 2 == 0 -0.8650  -1.4370 -0.2930</code></pre>
<p>E se quisermos as estimativas dos pesos médios para cada grupo? Para o grupo controle a estimativa é simplesmente o intercepto do modelo ajustado (beta0), e o resultado está no summary. Para o tratamento 1 devemos estimar beta0 + beta1 e para o tratamento 2 beta0 + beta2:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" title="1">L &lt;-<span class="st"> </span><span class="kw">rbind</span>(<span class="st">&#39;Trat 1&#39;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>),</a>
<a class="sourceLine" id="cb32-2" title="2">           <span class="st">&#39;Trat 2&#39;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>)); L</a></code></pre></div>
<pre><code>##        [,1] [,2] [,3]
## Trat 1    1    1    0
## Trat 2    1    0    1</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" title="1">g2 &lt;-<span class="st"> </span><span class="kw">glht</span>(ajuste2, <span class="dt">linfct =</span> L); g2</a></code></pre></div>
<pre><code>## 
##   General Linear Hypotheses
## 
## Linear Hypotheses:
##             Estimate
## Trat 1 == 0    4.661
## Trat 2 == 0    5.526</code></pre>
<p>estimativas pontuais para cada grupo.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb36-1" title="1"><span class="kw">summary</span>(g2)</a></code></pre></div>
<pre><code>## 
##   Simultaneous Tests for General Linear Hypotheses
## 
## Fit: lm(formula = weight ~ group, data = PlantGrowth)
## 
## Linear Hypotheses:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## Trat 1 == 0   4.6610     0.1971   23.64   &lt;1e-10 ***
## Trat 2 == 0   5.5260     0.1971   28.03   &lt;1e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## (Adjusted p values reported -- single-step method)</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" title="1"><span class="kw">confint</span>(g2)</a></code></pre></div>
<pre><code>## 
##   Simultaneous Confidence Intervals
## 
## Fit: lm(formula = weight ~ group, data = PlantGrowth)
## 
## Quantile = 2.3635
## 95% family-wise confidence level
##  
## 
## Linear Hypotheses:
##             Estimate lwr    upr   
## Trat 1 == 0 4.6610   4.1951 5.1269
## Trat 2 == 0 5.5260   5.0601 5.9919</code></pre>
<p>Intervalos de confiança.</p>
</div>
<div id="sem-intercepto" class="section level2">
<h2>Sem intercepto</h2>
<p>Agora vamos ajustar o modelo sem o intercepto.</p>
<p>contrasts(PlantGrowth$group) Padrão do R, contrastes de tratamentos, primeiro nível como referência.</p>
<p>Remoção do intercepto:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" title="1">ajuste4 &lt;-<span class="st"> </span><span class="kw">lm</span>(weight <span class="op">~</span><span class="st"> </span>group <span class="op">-</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> PlantGrowth)</a>
<a class="sourceLine" id="cb40-2" title="2"><span class="kw">model.matrix</span>(ajuste4)</a></code></pre></div>
<pre><code>##    grouptrt2 groupctrl grouptrt1
## 1          0         1         0
## 2          0         1         0
## 3          0         1         0
## 4          0         1         0
## 5          0         1         0
## 6          0         1         0
## 7          0         1         0
## 8          0         1         0
## 9          0         1         0
## 10         0         1         0
## 11         0         0         1
## 12         0         0         1
## 13         0         0         1
## 14         0         0         1
## 15         0         0         1
## 16         0         0         1
## 17         0         0         1
## 18         0         0         1
## 19         0         0         1
## 20         0         0         1
## 21         1         0         0
## 22         1         0         0
## 23         1         0         0
## 24         1         0         0
## 25         1         0         0
## 26         1         0         0
## 27         1         0         0
## 28         1         0         0
## 29         1         0         0
## 30         1         0         0
## attr(,&quot;assign&quot;)
## [1] 1 1 1
## attr(,&quot;contrasts&quot;)
## attr(,&quot;contrasts&quot;)$group
## [1] &quot;contr.treatment&quot;</code></pre>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" title="1"><span class="kw">summary</span>(ajuste4)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = weight ~ group - 1, data = PlantGrowth)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.0710 -0.4180 -0.0060  0.2627  1.3690 
## 
## Coefficients:
##           Estimate Std. Error t value Pr(&gt;|t|)    
## grouptrt2   5.5260     0.1971   28.03   &lt;2e-16 ***
## groupctrl   5.0320     0.1971   25.53   &lt;2e-16 ***
## grouptrt1   4.6610     0.1971   23.64   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.6234 on 27 degrees of freedom
## Multiple R-squared:  0.9867, Adjusted R-squared:  0.9852 
## F-statistic: 665.5 on 3 and 27 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb44-1" title="1"><span class="kw">confint</span>(ajuste4)</a></code></pre></div>
<pre><code>##              2.5 %   97.5 %
## grouptrt2 5.121526 5.930474
## groupctrl 4.627526 5.436474
## grouptrt1 4.256526 5.065474</code></pre>
<p>Cada estimativa agora corresponde à média sob uma das condições experimentais.</p>
</div>
<div id="outro-exemplo" class="section level2">
<h2>Outro exemplo</h2>
<p>Regressão com covariáveis quantitativas e qualitativas. Exemplo 1 - Dados de reação enzimática com células tratadas ou não com Puromycin. Nesse caso a variável qualitativa tem dois níveis (tratado ou não tratado).</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" title="1"><span class="kw">require</span>(ggplot2)</a>
<a class="sourceLine" id="cb46-2" title="2"></a>
<a class="sourceLine" id="cb46-3" title="3"><span class="kw">help</span>(<span class="st">&quot;Puromycin&quot;</span>)</a>
<a class="sourceLine" id="cb46-4" title="4"></a>
<a class="sourceLine" id="cb46-5" title="5"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> conc, <span class="dt">y =</span> rate, <span class="dt">color =</span> state), <span class="dt">data =</span> Puromycin) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb46-6" title="6"><span class="st">    </span><span class="kw">theme_bw</span>(<span class="dt">base_size =</span> <span class="dv">18</span>)</a></code></pre></div>
<p><img src="regressao_categorica_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" title="1"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> conc, <span class="dt">y =</span> rate), <span class="dt">data =</span> Puromycin) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb47-2" title="2"><span class="st">    </span><span class="kw">facet_grid</span>(<span class="op">~</span>state) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>(<span class="dt">base_size =</span> <span class="dv">18</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb47-3" title="3"><span class="st">    </span><span class="kw">xlab</span>(<span class="st">&#39;Concentração de substrato (ppm)&#39;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb47-4" title="4"><span class="st">    </span><span class="kw">ylab</span>(<span class="st">&#39;Taxa de reação (contagem/min^2)&#39;</span>)</a></code></pre></div>
<p><img src="regressao_categorica_files/figure-html/unnamed-chunk-13-2.png" width="672" /></p>
<p>A relação entre a concentração de substrato e a taxa de reação é claramente não linear. Vamos prosseguir a análise considerando transformação logarítmica para a concentração.</p>
</div>
<div id="ajuste-1" class="section level2">
<h2>Ajuste 1</h2>
<p>Vamos ajustar quatro modelos, em ordem crescente de complexidade.</p>
<p>Ajuste 1 - Modelo nulo, sem efeito de concentração.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb48-1" title="1">ajuste1 &lt;-<span class="st"> </span><span class="kw">lm</span>(rate <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> Puromycin)</a></code></pre></div>
</div>
<div id="ajuste-2" class="section level2">
<h2>Ajuste 2</h2>
<p>Ajuste2 - Modelo com efeito de concentração, sem efeito de tratamento.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" title="1">ajuste2 &lt;-<span class="st"> </span><span class="kw">lm</span>(rate <span class="op">~</span><span class="st"> </span><span class="kw">I</span>(<span class="kw">log2</span>(conc)), <span class="dt">data =</span> Puromycin)</a></code></pre></div>
</div>
<div id="ajuste-3" class="section level2">
<h2>Ajuste 3</h2>
<p>Ajuste3 - Modelo com efeitos aditivos de concentração e tratamento (sem interação)</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb50-1" title="1">ajuste3 &lt;-<span class="st"> </span><span class="kw">lm</span>(rate <span class="op">~</span><span class="st"> </span><span class="kw">I</span>(<span class="kw">log2</span>(conc)) <span class="op">+</span><span class="st"> </span>state, <span class="dt">data =</span> Puromycin)</a></code></pre></div>
</div>
<div id="ajuste-4" class="section level2">
<h2>Ajuste 4</h2>
<p>Ajuste4 - Modelo com efeito multiplicativo de concentração e tratamento (com interação)</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" title="1">ajuste4 &lt;-<span class="st"> </span><span class="kw">lm</span>(rate <span class="op">~</span><span class="st"> </span><span class="kw">I</span>(<span class="kw">log2</span>(conc)) <span class="op">*</span><span class="st"> </span>state, <span class="dt">data =</span> Puromycin)</a>
<a class="sourceLine" id="cb51-2" title="2"></a>
<a class="sourceLine" id="cb51-3" title="3"><span class="kw">anova</span>(ajuste1, ajuste2, ajuste3, ajuste4)</a></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: rate ~ 1
## Model 2: rate ~ I(log2(conc))
## Model 3: rate ~ I(log2(conc)) + state
## Model 4: rate ~ I(log2(conc)) * state
##   Res.Df   RSS Df Sum of Sq       F    Pr(&gt;F)    
## 1     22 49665                                   
## 2     21  6210  1     43455 518.870 2.955e-15 ***
## 3     20  2587  1      3623  43.258 2.695e-06 ***
## 4     19  1591  1       996  11.892  0.002692 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>De acordo com os resultados:</p>
<p>A adição da (log)concentração ao modelo nulo tem efeito significativo (F=518.87, p &lt; 0.001);</p>
<p>A adição do tratamento ao modelo ajustado pela (log) concentração tem efeito significativo (F=43.258, p &lt; 0.001);</p>
<p>A adição da interação entre tratamento e (log) concentração ao modelo aditivo tem efeito significativo (F=11.892, p = 0.0026).</p>
<p>Dessa forma, o modelo selecionado para descrever a relação entre a concentração de substrato e taxa de reação requer tanto interceptos quanto slopes distintos para cada tratamento.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" title="1"><span class="kw">summary</span>(ajuste4)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = rate ~ I(log2(conc)) * state, data = Puromycin)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -17.018  -6.381  -1.005   7.616  13.323 
## 
## Coefficients:
##                              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                   209.194      4.453  46.974  &lt; 2e-16 ***
## I(log2(conc))                  25.723      1.364  18.858 9.25e-14 ***
## stateuntreated                -44.606      6.811  -6.549 2.85e-06 ***
## I(log2(conc)):stateuntreated   -7.020      2.036  -3.448  0.00269 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.151 on 19 degrees of freedom
## Multiple R-squared:  0.968,  Adjusted R-squared:  0.9629 
## F-statistic: 191.3 on 3 and 19 DF,  p-value: 2.267e-14</code></pre>
<p>Gráficos de resíduos</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb55-1" title="1"><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb55-2" title="2"><span class="kw">plot</span>(ajuste4)</a></code></pre></div>
<p><img src="regressao_categorica_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>Acrescente seus comentários, produza resultados complementares.</p>
<p>Vamos plotar os ajustes. Para isso, primeiro vamos criar uma base para predição.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb56-1" title="1">new_conc &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="kw">min</span>(Puromycin<span class="op">$</span>conc), <span class="kw">max</span>(Puromycin<span class="op">$</span>conc), <span class="dt">length.out =</span> <span class="dv">100</span>)</a>
<a class="sourceLine" id="cb56-2" title="2">trat &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;treated&#39;</span>, <span class="st">&#39;untreated&#39;</span>)</a>
<a class="sourceLine" id="cb56-3" title="3">new_data &lt;-<span class="st"> </span><span class="kw">expand.grid</span>(new_conc, trat)</a>
<a class="sourceLine" id="cb56-4" title="4"><span class="kw">names</span>(new_data) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;conc&#39;</span>, <span class="st">&#39;state&#39;</span>)</a></code></pre></div>
<p>Agora o gráfico.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb57-1" title="1"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> conc, <span class="dt">y =</span> rate), <span class="dt">data =</span> Puromycin) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb57-2" title="2"><span class="st">    </span><span class="kw">facet_grid</span>(<span class="op">~</span>state) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>(<span class="dt">base_size =</span> <span class="dv">18</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb57-3" title="3"><span class="st">    </span><span class="kw">xlab</span>(<span class="st">&#39;Concentração de substrato (ppm)&#39;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb57-4" title="4"><span class="st">    </span><span class="kw">ylab</span>(<span class="st">&#39;Taxa de reação (contagem/min^2)&#39;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb57-5" title="5"><span class="st">    </span><span class="kw">geom_line</span>(<span class="dt">data =</span> new_data, </a>
<a class="sourceLine" id="cb57-6" title="6">          <span class="kw">aes</span>(<span class="dt">x =</span> conc, <span class="dt">y=</span><span class="kw">predict</span>(ajuste4, <span class="dt">newdata=</span>new_data)), </a>
<a class="sourceLine" id="cb57-7" title="7">          <span class="dt">color=</span><span class="st">&#39;blue&#39;</span>)</a></code></pre></div>
<p><img src="regressao_categorica_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
</div>
<div id="outro-exemplo-1" class="section level2">
<h2>Outro exemplo</h2>
<p>Regressão com covariáveis quantitativas e qualitativas. Exemplo 2 - Dados de logevidade de moscas machos submetidas a diferentes condições experimentais. Consulte a documentação.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" title="1"><span class="kw">require</span>(faraway)</a>
<a class="sourceLine" id="cb58-2" title="2"><span class="kw">help</span>(<span class="st">&quot;fruitfly&quot;</span>)</a>
<a class="sourceLine" id="cb58-3" title="3"></a>
<a class="sourceLine" id="cb58-4" title="4"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> thorax, <span class="dt">y =</span> longevity, <span class="dt">color =</span> activity), <span class="dt">data =</span> fruitfly) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb58-5" title="5"><span class="st">    </span><span class="kw">theme_bw</span>(<span class="dt">base_size =</span> <span class="dv">18</span>)</a></code></pre></div>
<p><img src="regressao_categorica_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" title="1"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> thorax, <span class="dt">y =</span> longevity), <span class="dt">data =</span> fruitfly) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb59-2" title="2"><span class="st">    </span><span class="kw">facet_grid</span>(<span class="op">~</span>activity) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>(<span class="dt">base_size =</span> <span class="dv">18</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb59-3" title="3"><span class="st">    </span><span class="kw">xlab</span>(<span class="st">&#39;Tamanho do torax&#39;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb59-4" title="4"><span class="st">    </span><span class="kw">ylab</span>(<span class="st">&#39;Tempo de vida (em dias)&#39;</span>)</a></code></pre></div>
<p><img src="regressao_categorica_files/figure-html/unnamed-chunk-22-2.png" width="672" /></p>
<p>Vamos ajustar quatro modelos, em ordem crescente de complexidade.</p>
</div>
<div id="ajuste-1-1" class="section level2">
<h2>Ajuste 1</h2>
<p>Ajuste 1 - Modelo nulo, sem efeito de concentração.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" title="1">ajuste1 &lt;-<span class="st"> </span><span class="kw">lm</span>(longevity <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> fruitfly)</a></code></pre></div>
</div>
<div id="ajuste-2-1" class="section level2">
<h2>Ajuste 2</h2>
<p>Ajuste2 - Modelo com efeito de concentração, sem efeito de tratamento.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb61-1" title="1">ajuste2 &lt;-<span class="st"> </span><span class="kw">lm</span>(longevity <span class="op">~</span><span class="st"> </span>thorax, <span class="dt">data =</span> fruitfly)</a></code></pre></div>
</div>
<div id="ajuste-3-1" class="section level2">
<h2>Ajuste 3</h2>
<p>Ajuste3 - Modelo com efeitos aditivos de concentração e tratamento (sem interação)</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb62-1" title="1">ajuste3 &lt;-<span class="st"> </span><span class="kw">lm</span>(longevity <span class="op">~</span><span class="st"> </span>thorax <span class="op">+</span><span class="st"> </span>activity, <span class="dt">data =</span> fruitfly)</a></code></pre></div>
</div>
<div id="ajuste-4-1" class="section level2">
<h2>Ajuste 4</h2>
<p>Ajuste4 - Modelo com efeito multiplicativo de concentração e tratamento (com interação)</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb63-1" title="1">ajuste4 &lt;-<span class="st"> </span><span class="kw">lm</span>(longevity <span class="op">~</span><span class="st"> </span>thorax <span class="op">*</span><span class="st"> </span>activity, <span class="dt">data =</span> fruitfly)</a>
<a class="sourceLine" id="cb63-2" title="2"></a>
<a class="sourceLine" id="cb63-3" title="3"><span class="kw">anova</span>(ajuste1, ajuste2, ajuste3, ajuste4)</a></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: longevity ~ 1
## Model 2: longevity ~ thorax
## Model 3: longevity ~ thorax + activity
## Model 4: longevity ~ thorax * activity
##   Res.Df   RSS Df Sum of Sq       F    Pr(&gt;F)    
## 1    123 37745                                   
## 2    122 22742  1   15003.3 130.733 &lt; 2.2e-16 ***
## 3    118 13107  4    9634.6  20.988 5.503e-13 ***
## 4    114 13083  4      24.3   0.053    0.9947    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>De acordo com os resultados:</p>
<p>A adição do tamanho do torax ao modelo nulo tem efeito significativo (F=130.733, p &lt; 0.001);</p>
<p>A adição do tratamento ao modelo ajustado pelo tamanho do torax tem efeito significativo (F=20.988, p &lt; 0.001);</p>
<p>A adição da interação entre tamanho do torax e tratamento ao modelo aditivo não tem efeito significativo (F=0.053, p = 0.9947).</p>
<p>Dessa forma, o modelo selecionado para descrever a relação entre a concentração de substrato e taxa de reação requer um intercepto para cada tratamento, mas um único slope.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb65-1" title="1"><span class="kw">summary</span>(ajuste3)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = longevity ~ thorax + activity, data = fruitfly)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -26.108  -7.014  -1.101   6.234  30.265 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   -48.749     10.850  -4.493 1.65e-05 ***
## thorax        134.341     12.731  10.552  &lt; 2e-16 ***
## activityone     2.637      2.984   0.884   0.3786    
## activitylow    -7.015      2.981  -2.353   0.0203 *  
## activitymany    4.139      3.027   1.367   0.1741    
## activityhigh  -20.004      3.016  -6.632 1.05e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.54 on 118 degrees of freedom
## Multiple R-squared:  0.6527, Adjusted R-squared:  0.638 
## F-statistic: 44.36 on 5 and 118 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Gráficos de resíduos</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb67-1" title="1"><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb67-2" title="2"><span class="kw">plot</span>(ajuste3)</a></code></pre></div>
<p><img src="regressao_categorica_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>Os resíduos visivelmente não tem variância constante. Fica como tarefa encontrar uma transformação que contorne isso. Como o objetivo aqui é simplesmente obter as restas ajustadas (sem procupação quanto aos erros ou outras inferências, prosseguimos com o modelo original.)</p>
<p>Vamos plotar os ajustes. Para isso, primeiro vamos criar uma base para predição.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb68-1" title="1">new_thorax &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="kw">min</span>(fruitfly<span class="op">$</span>thorax), <span class="kw">max</span>(fruitfly<span class="op">$</span>thorax), <span class="dt">length.out =</span> <span class="dv">100</span>)</a>
<a class="sourceLine" id="cb68-2" title="2">trat &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;isolated&#39;</span>, <span class="st">&#39;one&#39;</span>, <span class="st">&#39;low&#39;</span>, <span class="st">&#39;many&#39;</span>, <span class="st">&#39;high&#39;</span>)</a>
<a class="sourceLine" id="cb68-3" title="3">new_data &lt;-<span class="st"> </span><span class="kw">expand.grid</span>(new_thorax, trat)</a>
<a class="sourceLine" id="cb68-4" title="4"><span class="kw">names</span>(new_data) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;thorax&#39;</span>, <span class="st">&#39;activity&#39;</span>)</a></code></pre></div>
<p>Agora o gráfico.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb69-1" title="1"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> thorax, <span class="dt">y =</span> longevity), <span class="dt">data =</span> fruitfly) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb69-2" title="2"><span class="st">    </span><span class="kw">facet_grid</span>(<span class="op">~</span>activity) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>(<span class="dt">base_size =</span> <span class="dv">18</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb69-3" title="3"><span class="st">    </span><span class="kw">xlab</span>(<span class="st">&#39;Concentração de substrato (ppm)&#39;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb69-4" title="4"><span class="st">    </span><span class="kw">ylab</span>(<span class="st">&#39;Taxa de reação (contagem/min^2)&#39;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb69-5" title="5"><span class="st">    </span><span class="kw">geom_smooth</span>(<span class="dt">method=</span><span class="st">&#39;lm&#39;</span>)</a></code></pre></div>
<p><img src="regressao_categorica_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb70-1" title="1">fruitfly<span class="op">$</span>activity2 &lt;-<span class="st"> </span>fruitfly<span class="op">$</span>activity </a>
<a class="sourceLine" id="cb70-2" title="2"><span class="kw">levels</span>(fruitfly<span class="op">$</span>activity2) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;iso or preg&#39;</span>, <span class="st">&#39;iso or preg&#39;</span>, <span class="st">&#39;virg1&#39;</span>, <span class="st">&#39;iso or preg&#39;</span>, <span class="st">&#39;virg2&#39;</span>)</a>
<a class="sourceLine" id="cb70-3" title="3">ajuste3_alt &lt;-<span class="st"> </span><span class="kw">lm</span>(longevity <span class="op">~</span><span class="st"> </span>thorax <span class="op">+</span><span class="st"> </span>activity2, <span class="dt">data =</span> fruitfly)</a>
<a class="sourceLine" id="cb70-4" title="4"><span class="kw">summary</span>(ajuste3_alt)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = longevity ~ thorax + activity2, data = fruitfly)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -25.6102  -7.5189  -0.4157   6.3342  30.6952 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     -45.110     10.518  -4.289 3.65e-05 ***
## thorax          132.637     12.665  10.473  &lt; 2e-16 ***
## activity2virg1   -9.226      2.443  -3.777 0.000248 ***
## activity2virg2  -22.279      2.458  -9.066 2.87e-15 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.54 on 120 degrees of freedom
## Multiple R-squared:  0.6471, Adjusted R-squared:  0.6383 
## F-statistic: 73.34 on 3 and 120 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb72-1" title="1"><span class="kw">anova</span>(ajuste3_alt, ajuste3)</a></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: longevity ~ thorax + activity2
## Model 2: longevity ~ thorax + activity
##   Res.Df   RSS Df Sum of Sq      F Pr(&gt;F)
## 1    120 13321                           
## 2    118 13107  2    213.89 0.9628 0.3848</code></pre>
<p>Vamos testar agora se uma única reta de regressão é suficiente para explicar a relação entre longevidade e tamanho do torax para controle e para os dois grupos expostos a fêmeas grávidas.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb74-1" title="1">fruitfly<span class="op">$</span>activity2 &lt;-<span class="st"> </span>fruitfly<span class="op">$</span>activity </a>
<a class="sourceLine" id="cb74-2" title="2"><span class="kw">levels</span>(fruitfly<span class="op">$</span>activity2) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;iso or preg&#39;</span>, <span class="st">&#39;iso or preg&#39;</span>, <span class="st">&#39;low&#39;</span>, <span class="st">&#39;iso or preg&#39;</span>, <span class="st">&#39;high&#39;</span>)</a></code></pre></div>
<p>O fator activity2 tem três níveis: ‘iso or preg’ para animais do grupo controle e submetidos a fêmeas grávidas; ‘low’ e ‘high’ para os outros dois grupos.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb75-1" title="1">ajuste3_alt &lt;-<span class="st"> </span><span class="kw">lm</span>(longevity <span class="op">~</span><span class="st"> </span>thorax <span class="op">+</span><span class="st"> </span>activity2, <span class="dt">data =</span> fruitfly)</a></code></pre></div>
<p>Modelo de regressão ajustado para o tratamento com três níveis.</p>
<p>Vamos comparar os ajustes dos modelos considerando o tratamento com cinco e com três níveis.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb76-1" title="1"><span class="kw">summary</span>(ajuste3_alt)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = longevity ~ thorax + activity2, data = fruitfly)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -25.6102  -7.5189  -0.4157   6.3342  30.6952 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    -45.110     10.518  -4.289 3.65e-05 ***
## thorax         132.637     12.665  10.473  &lt; 2e-16 ***
## activity2low    -9.226      2.443  -3.777 0.000248 ***
## activity2high  -22.279      2.458  -9.066 2.87e-15 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.54 on 120 degrees of freedom
## Multiple R-squared:  0.6471, Adjusted R-squared:  0.6383 
## F-statistic: 73.34 on 3 and 120 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb78-1" title="1"><span class="kw">anova</span>(ajuste3_alt, ajuste3)</a></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: longevity ~ thorax + activity2
## Model 2: longevity ~ thorax + activity
##   Res.Df   RSS Df Sum of Sq      F Pr(&gt;F)
## 1    120 13321                           
## 2    118 13107  2    213.89 0.9628 0.3848</code></pre>
<p>Observe que o acréscimo na soma de quadrados resultante da redução de cinco para três níveis do tratamento é não significativa (p=0.3848). Assim, podemos considerar o modelo aditivo com uma única reta de regressão para os grupos ‘isolated’, ‘one’ e ‘many’.</p>
<p>Vamos plotar os resultados do ajuste, como feito anteriormente.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb80-1" title="1">new_thorax &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="kw">min</span>(fruitfly<span class="op">$</span>thorax), <span class="kw">max</span>(fruitfly<span class="op">$</span>thorax), <span class="dt">length.out =</span> <span class="dv">100</span>)</a>
<a class="sourceLine" id="cb80-2" title="2">trat &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;virg1&#39;</span>, <span class="st">&#39;iso or preg&#39;</span>, <span class="st">&#39;virg2&#39;</span>)</a>
<a class="sourceLine" id="cb80-3" title="3">new_data &lt;-<span class="st"> </span><span class="kw">expand.grid</span>(new_thorax, trat)</a>
<a class="sourceLine" id="cb80-4" title="4"><span class="kw">names</span>(new_data) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;thorax&#39;</span>, <span class="st">&#39;activity2&#39;</span>)</a>
<a class="sourceLine" id="cb80-5" title="5"></a>
<a class="sourceLine" id="cb80-6" title="6"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> thorax, <span class="dt">y =</span> longevity), <span class="dt">data =</span> fruitfly) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb80-7" title="7"><span class="st">    </span><span class="kw">facet_grid</span>(<span class="op">~</span>activity2) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>(<span class="dt">base_size =</span> <span class="dv">18</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb80-8" title="8"><span class="st">    </span><span class="kw">xlab</span>(<span class="st">&#39;Concentração de substrato (ppm)&#39;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb80-9" title="9"><span class="st">    </span><span class="kw">ylab</span>(<span class="st">&#39;Taxa de reação (contagem/min^2)&#39;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb80-10" title="10"><span class="st">    </span><span class="kw">geom_smooth</span>(<span class="dt">method=</span><span class="st">&#39;lm&#39;</span>)</a></code></pre></div>
<p><img src="regressao_categorica_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
